### ISSUE TITLE
Rebuild oereb-server.database.base?

### ISSUE THREAD

**Issue by romefi** [agiktsh/oereb-server.database.base#1]
@vvmruder Können wir den oereb-server.database.base ebenfalls manuell rebuilden, so wie das bei https://github.com/agiktsh/oereb-server.database/actions/workflows/full-rebuild-database.yml geht?

Falls das einfach möglich wären, wären wir froh drum, um Anpassungen an Katalogen zeitnah zu testen.

**Comment by vvmruder** [comment]
@romefi Ja das geht: 
![image](https://github.com/agiktsh/oereb-server.database.base/assets/3714179/f31588da-6c55-4078-b39d-69d634de3222)

Momentan ist das Repo noch hier: https://github.com/openoereb/ch.sh.oereb_base

Dort unter Actions kann das auch manuell ausgelöst werden.

**Comment by romefi** [comment]
Danke für die Info 👍
